"""Attendance Service Schemas package."""

from .attendance import (
    GPSEventCreate,
    GPSEventResponse,
    AttendanceRecordCreate,
    AttendanceRecordUpdate,
    AttendanceRecordResponse,
    GPSProcessingResult,
    AttendanceSessionCreate,
    AttendanceSessionResponse,
    AttendanceReportRequest,
    AttendanceStats,
    UserAttendanceReport,
    CourseAttendanceReport,
    AttendanceNotification,
    BaseResponse,
    GPSEventCreateResponse,
    AttendanceListResponse,
    ErrorResponse,
    CoordinateValidation,
    DistanceCalculation,
)

__all__ = [
    "GPSEventCreate",
    "GPSEventResponse",
    "AttendanceRecordCreate",
    "AttendanceRecordUpdate",
    "AttendanceRecordResponse",
    "GPSProcessingResult",
    "AttendanceSessionCreate",
    "AttendanceSessionResponse",
    "AttendanceReportRequest",
    "AttendanceStats",
    "UserAttendanceReport",
    "CourseAttendanceReport",
    "AttendanceNotification",
    "BaseResponse",
    "GPSEventCreateResponse",
    "AttendanceListResponse",
    "ErrorResponse",
    "CoordinateValidation",
    "DistanceCalculation",
]