server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Configuraciones almacenadas localmente
          search-locations: classpath:/config
        # Configuraci칩n para refresh autom치tico
        default-label: main
  security:
    user:
      name: config-user
      password: config-pass

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: config-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,configprops
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"

# Configuraci칩n de encriptaci칩n para datos sensibles
encrypt:
  key: geoattend-secret-key-2025