# Configuración específica para User Service
server:
  port: 8081

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      default_schema: user_schema
  flyway:
    schemas: user_schema
    locations: classpath:db/migration/user

# Configuración específica de JWT para autenticación
jwt:
  issuer: geoattend-user-service

# Configuración de validación
validation:
  user:
    code:
      pattern: "^[0-9]{10}[A-Z]$" # Ejemplo: 2020010101A
      message: "Código de usuario debe tener 10 dígitos seguidos de una letra"
    password:
      min-length: 8
      require-uppercase: true
      require-lowercase: true
      require-digits: true

# Rate limiting para endpoints sensibles
rate-limit:
  login:
    requests-per-minute: 5
  register:
    requests-per-minute: 3

logging:
  level:
    com.geoattend.user: DEBUG