"""Course Service Schemas package."""

from .course import (
    CourseCreate,
    CourseUpdate,
    CourseResponse,
    CourseDetailResponse,
    ClassroomCreate,
    ClassroomUpdate,
    ClassroomResponse,
    CourseClassroomCreate,
    CourseClassroomUpdate,
    CourseClassroomResponse,
    ScheduleCreate,
    ScheduleResponse,
    EnrollmentCreate,
    EnrollmentResponse,
    CourseCoordinates,
    BaseResponse,
    CourseCreateResponse,
    CourseListResponse,
    ErrorResponse,
)

__all__ = [
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseDetailResponse",
    "ClassroomCreate",
    "ClassroomUpdate",
    "ClassroomResponse",
    "CourseClassroomCreate",
    "CourseClassroomUpdate",
    "CourseClassroomResponse",
    "ScheduleCreate",
    "ScheduleResponse",
    "EnrollmentCreate",
    "EnrollmentResponse",
    "CourseCoordinates",
    "BaseResponse",
    "CourseCreateResponse",
    "CourseListResponse",
    "ErrorResponse",
]